makechrootpkg-ike :: updated to be on par with devtools
Signed-off-by: BlackEagle <ike.devolder@gmail.com>

diff --git a/makechrootpkg-ike b/makechrootpkg-ike
--- a/makechrootpkg-ike
+++ b/makechrootpkg-ike
@@ -8,28 +8,158 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
-FORCE='n'
-RUN=''
-MAKEPKG_ARGS='-s --noconfirm'
-#COPY='copy'
+# set workdir for binding
 WORKDIR=$PWD
 
-update_first='0'
-clean_first='0'
-install_before=''
-install_pkg=''
-add_to_db=0
+# Avoid any encoding problems
+export LANG=C
 
-chrootdir=''
+# check if messages are to be printed using color
+unset ALL_OFF BOLD BLUE GREEN RED YELLOW
+if [[ -t 2 ]]; then
+	# prefer terminal safe colored and bold text when tput is supported
+	if tput setaf 0 &>/dev/null; then
+		ALL_OFF="$(tput sgr0)"
+		BOLD="$(tput bold)"
+		BLUE="${BOLD}$(tput setaf 4)"
+		GREEN="${BOLD}$(tput setaf 2)"
+		RED="${BOLD}$(tput setaf 1)"
+		YELLOW="${BOLD}$(tput setaf 3)"
+	else
+		ALL_OFF="\e[1;0m"
+		BOLD="\e[1;1m"
+		BLUE="${BOLD}\e[1;34m"
+		GREEN="${BOLD}\e[1;32m"
+		RED="${BOLD}\e[1;31m"
+		YELLOW="${BOLD}\e[1;33m"
+	fi
+fi
+readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
 
-APPNAME=$(basename "${0}")
+plain() {
+	local mesg=$1; shift
+	printf "${BOLD}    ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+msg2() {
+	local mesg=$1; shift
+	printf "${BLUE}  ->${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+warning() {
+	local mesg=$1; shift
+	printf "${YELLOW}==> WARNING:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+error() {
+	local mesg=$1; shift
+	printf "${RED}==> ERROR:${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}\n" "$@" >&2
+}
+
+stat_busy() {
+	local mesg=$1; shift
+	printf "${GREEN}==>${ALL_OFF}${BOLD} ${mesg}...${ALL_OFF}" >&2
+}
+
+stat_done() {
+	printf "${BOLD}done${ALL_OFF}\n" >&2
+}
+
+cleanup() {
+	trap - EXIT INT QUIT TERM
+
+	unbind
+	[[ $1 ]] && exit $1
+}
+
+unbind() {
+	for u in 'pkgdest' 'srcdest' 'build'; do
+		if df -ah | grep ${copydir}/${u}> /dev/null 2>&1; then
+			umount ${copydir}/${u}
+		fi
+	done
+}
+
+
+abort() {
+	msg 'Aborting...'
+	cleanup 0
+}
+
+die() {
+	error "$*"
+	cleanup 1
+}
+
+trap abort INT QUIT TERM HUP
+trap 'cleanup 0' EXIT
+
+##
+#  usage : in_array( $needle, $haystack )
+# return : 0 - found
+#          1 - not found
+##
+in_array() {
+	local needle=$1; shift
+	local item
+	for item in "$@"; do
+		[[ $item = $needle ]] && return 0 # Found
+	done
+	return 1 # Not Found
+}
+
+##
+#  usage : get_full_version( [$pkgname] )
+# return : full version spec, including epoch (if necessary), pkgver, pkgrel
+##
+get_full_version() {
+	# set defaults if they weren't specified in buildfile
+	pkgbase=${pkgbase:-${pkgname[0]}}
+	epoch=${epoch:-0}
+	if [[ -z $1 ]]; then
+		if [[ $epoch ]] && (( ! $epoch )); then
+			echo $pkgver-$pkgrel
+		else
+			echo $epoch:$pkgver-$pkgrel
+		fi
+	else
+		for i in pkgver pkgrel epoch; do
+			local indirect="${i}_override"
+			eval $(declare -f package_$1 | sed -n "s/\(^[[:space:]]*$i=\)/${i}_override=/p")
+			[[ -z ${!indirect} ]] && eval ${indirect}=\"${!i}\"
+		done
+		if (( ! $epoch_override )); then
+			echo $pkgver_override-$pkgrel_override
+		else
+			echo $epoch_override:$pkgver_override-$pkgrel_override
+		fi
+	fi
+}
+
+
+shopt -s nullglob
+
+makepkg_args='-s --noconfirm'
+update_first=false
+clean_first=false
+install_pkg=
+install_before=
+add_to_db=false
+run_namcap=false
+chrootdir=
+passeddir=
 
 default_copy=$USER
 [[ -n $SUDO_USER ]] && default_copy=$SUDO_USER
 [[ -z $default_copy || $default_copy = root ]] && default_copy=copy
 
 usage() {
-	echo "usage ${APPNAME} [options] -r <chrootdir> [--] [makepkg args]"
+	echo "usage ${0##*/} [options] -r <chrootdir> [--] [makepkg args]"
 	echo ' Run this script in a PKGBUILD dir to build a package inside a'
 	echo ' clean chroot. All unrecognized arguments passed to this script'
 	echo ' will be passed to makepkg.'
@@ -42,7 +172,7 @@ usage() {
 	echo 'command:'
 	echo '    mkarchroot <chrootdir>/root base base-devel sudo'
 	echo ''
-	echo "Default makepkg args: $MAKEPKG_ARGS"
+	echo "Default makepkg args: $makepkg_args"
 	echo ''
 	echo 'Flags:'
 	echo '-h         This help'
@@ -57,59 +187,52 @@ usage() {
 	echo '-l <copy>  The directory to use as the working copy of the chroot'
 	echo '           Useful for maintaining multiple copies.'
 	echo "           Default: $default_copy"
+	echo '-n         Run namcap on the package'
 	exit 1
 }
 
-unbind() {
-	for u in 'pkgdest' 'srcdest' 'build'; do
-		if df -ah | grep ${copydir}/${u}> /dev/null 2>&1; then
-			umount ${copydir}/${u}
-		fi
-	done
-}
-
-while getopts 'hcuy:dr:I:l:' arg; do
-	case "${arg}" in
+while getopts 'hcudr:I:l:n' arg; do
+	case "$arg" in
 		h) usage ;;
-		c) clean_first=1 ;;
-		u) update_first=1 ;;
-		y) install_before="$OPTARG" ;;
-		d) add_to_db=1 ;;
-		r) chrootdir="$OPTARG" ;;
+		c) clean_first=true ;;
+		u) update_first=true ;;
+		d) add_to_db=true ;;
+		r) passeddir="$OPTARG" ;;
 		I) install_pkg="$OPTARG" ;;
+		y) install_before="$OPTARG" ;;
 		l) copy="$OPTARG" ;;
-		*) MAKEPKG_ARGS="$MAKEPKG_ARGS -$arg $OPTARG" ;;
+		n) run_namcap=true; makepkg_args="$makepkg_args -i" ;;
+		*) makepkg_args="$makepkg_args -$arg $OPTARG" ;;
 	esac
 done
 
 # Canonicalize chrootdir, getting rid of trailing /
-chrootdir=$(readlink -e "$chrootdir")
+chrootdir=$(readlink -e "$passeddir")
 
-[[ -z $copy ]] && copy=$default_copy
-copydir="$chrootdir/$copy"
+if [[ ${copy:0:1} = / ]]; then
+	copydir=$copy
+else
+	[[ -z $copy ]] && copy=$default_copy
+	copydir="$chrootdir/$copy"
+fi
 
 # Pass all arguments after -- right to makepkg
-MAKEPKG_ARGS="$MAKEPKG_ARGS ${*:$OPTIND}"
+makepkg_args="$makepkg_args ${*:$OPTIND}"
 
-if [ "$EUID" != '0' ]; then
-	echo 'This script must be run as root.'
-	exit 1
+if (( EUID )); then
+	die 'This script must be run as root.'
 fi
 
-if [ ! -f PKGBUILD -a -z "$install_pkg" ]; then
-	echo 'This must be run in a directory containing a PKGBUILD.'
-	exit 1
+if [[ ! -f PKGBUILD && -z $install_pkg ]]; then
+	die 'This must be run in a directory containing a PKGBUILD.'
 fi
 
-if [ ! -d "$chrootdir" ]; then
-	echo "No chroot dir defined, or invalid path '$chrootdir'"
-	exit 1
+if [[ ! -d $chrootdir ]]; then
+	die "No chroot dir defined, or invalid path '$passeddir'"
 fi
 
-if [ ! -d "$chrootdir/root" ]; then
-	echo 'Missing chroot dir root directory.'
-	echo "Try using: mkarchroot $chrootdir/root base base-devel sudo"
-	usage
+if [[ ! -d $chrootdir/root ]]; then
+	die "Missing chroot dir root directory. Try using: mkarchroot $chrootdir/root base base-devel sudo"
 fi
 
 umask 0022
@@ -118,27 +241,28 @@ umask 0022
 # Note this is the same FD number as in mkarchroot
 exec 9>"$copydir.lock"
 if ! flock -n 9; then
-	echo -n "locking chroot copy '$copy'..."
+	stat_busy "Locking chroot copy '$copy'"
 	flock 9
-	echo "done"
+	stat_done
 fi
 
-if [ ! -d "$copydir" -o "$clean_first" -eq "1" ]; then
+if [[ ! -d $copydir ]] || $clean_first; then
 	# Get a read lock on the root chroot to make
 	# sure we don't clone a half-updated chroot
 	exec 8>"$chrootdir/root.lock"
 
 	if ! flock -sn 8; then
-		echo -n "locking clean chroot..."
+		stat_busy "Locking clean chroot"
 		flock -s 8
-		echo "done"
+		stat_done
 	fi
 
-	echo -n 'creating clean working copy...'
+	stat_busy 'Creating clean working copy'
 	use_rsync=false
 	if type -P btrfs >/dev/null; then
-		[ -d $copydir ] && btrfs subvolume delete "$copydir" &>/dev/null
-		btrfs subvolume snapshot "$chrootdir/root" "$copydir" &>/dev/null || use_rsync=true
+		[[ -d $copydir ]] && btrfs subvolume delete "$copydir" &>/dev/null
+		btrfs subvolume snapshot "$chrootdir/root" "$copydir" &>/dev/null ||
+			use_rsync=true
 	else
 		use_rsync=true
 	fi
@@ -147,92 +271,89 @@ if [ ! -d "$copydir" -o "$clean_first" -eq "1" ]; then
 		mkdir -p "$copydir"
 		rsync -a --delete -q -W -x "$chrootdir/root/" "$copydir"
 	fi
-	echo 'done'
+	stat_done
 
 	# Drop the read lock again
 	exec 8>&-
 fi
 
-if [ -n "$install_pkg" ]; then
-	pkgname="$(basename "$install_pkg")"
+if [[ -n $install_pkg ]]; then
+	pkgname="${install_pkg##*/}"
 	cp "$install_pkg" "$copydir/$pkgname"
-	mkarchroot -r "pacman -U /$pkgname" "$copydir"
+
+	mkarchroot -r "pacman -U /$pkgname --noconfirm" "$copydir"
 	ret=$?
+
 	rm "$copydir/$pkgname"
+
 	# Exit early, we've done all we need to
 	exit $ret
 fi
 
-if [ $update_first -eq 1 ]; then
-	mkarchroot -u "$copydir"
-fi
+$update_first && mkarchroot -u "$copydir"
+[[ $install_before != '' ]] && mkarchroot -r "pacman -S --noconfirm $install_before" "$copydir"
 
-if [ "$install_before" != "" ]; then
-	mkarchroot -r "pacman -S --noconfirm $install_before" "$copydir"
-fi
-
+[[ ! -d "$copydir/build" ]] && mkdir -p "$copydir/build"
 # bind build dir
-[ -d "$copydir/build" ] || mkdir "$copydir/build"
 mount -o bind ${WORKDIR} ${copydir}/build
 
-# read .makpekg.conf even if called via sudo
-if [ -n "${SUDO_USER}" ]; then
-	makepkg_conf="/$(eval echo ~${SUDO_USER})/.makepkg.conf"
+# Read .makepkg.conf and .gnupg/pubring.gpg even if called via sudo
+if [[ -n $SUDO_USER ]]; then
+	SUDO_HOME="$(eval echo ~$SUDO_USER)"
+	makepkg_conf="$SUDO_HOME/.makepkg.conf"
+	if [[ -r "$SUDO_HOME/.gnupg/pubring.gpg" ]]; then
+		install -D "$SUDO_HOME/.gnupg/pubring.gpg" "$copydir/build/.gnupg/pubring.gpg"
+	fi
 else
-	makepkg_conf="~/.makepkg.conf"
+	makepkg_conf="$HOME/.makepkg.conf"
+	if [[ -r "$HOME/.gnupg/pubring.gpg" ]]; then
+		install -D "$HOME/.gnupg/pubring.gpg" "$copydir/build/.gnupg/pubring.gpg"
+	fi
 fi
 
 # Get SRC/PKGDEST from makepkg.conf
-if [ -f "${makepkg_conf}" ]; then
-	eval $(grep '^SRCDEST=' "${makepkg_conf}")
-	eval $(grep '^PKGDEST=' "${makepkg_conf}")
-
-	eval $(grep '^MAKEFLAGS=' "${makepkg_conf}")
-	eval $(grep '^PACKAGER=' "${makepkg_conf}")
+if [[ -f $makepkg_conf ]]; then
+	eval $(grep '^SRCDEST=' "$makepkg_conf")
+	eval $(grep '^PKGDEST=' "$makepkg_conf")
+	eval $(grep '^MAKEFLAGS=' "$makepkg_conf")
+	eval $(grep '^PACKAGER=' "$makepkg_conf")
 fi
-[ -z "${SRCDEST}" ] && eval $(grep '^SRCDEST=' /etc/makepkg.conf)
-[ -z "${PKGDEST}" ] && eval $(grep '^PKGDEST=' /etc/makepkg.conf)
 
-# check if PKGDEST is set, if not symlink pkgdest to build dir
-#if [ -z "${PKGDEST}" ]; then
-#	(cd ${copydir}; ln -s build pkgdest)
-#else
-#	mkdir ${copydir}/pkgdest
-#	mount -o bind ${PKGDEST} ${copydir}/pkgdest
-#fi
-if [ ! -z "${PKGDEST}" ]; then
-	if ! grep 'PKGDEST="/pkgdest"' "$copydir/etc/makepkg.conf" >/dev/null 2>&1; then
+[[ -z $SRCDEST ]] && eval $(grep '^SRCDEST=' /etc/makepkg.conf)
+[[ -z $PKGDEST ]] && eval $(grep '^PKGDEST=' /etc/makepkg.conf)
+[[ -z $MAKEFLAGS ]] && eval $(grep '^MAKEFLAGS=' /etc/makepkg.conf)
+[[ -z $PACKAGER ]] && eval $(grep '^PACKAGER=' /etc/makepkg.conf)
+
+# Use PKGBUILD directory if PKGDEST or SRCDEST don't exist
+[[ -d $PKGDEST ]] || PKGDEST=.
+[[ -d $SRCDEST ]] || SRCDEST=.
+
+if [[ ! -z "${PKGDEST}" ]]; then
+	[[ ! -d "$copydir/pkgdest" ]] && mkdir -p "$copydir/pkgdest"
+	if ! grep -q 'PKGDEST="/pkgdest"' "$copydir/etc/makepkg.conf"; then
 		echo 'PKGDEST="/pkgdest"' >> "$copydir/etc/makepkg.conf"
 	fi
-	[ ! -d ${copydir}/pkgdest ] && mkdir ${copydir}/pkgdest
+
 	mount -o bind ${PKGDEST} ${copydir}/pkgdest
 fi
 
-# check if SRCDEST is set, if not symlink srcdest to build dir
-#if [ -z "${SRCDEST}" ]; then
-#	(cd ${copydir}; ln -s build srcdest)
-#else
-#	mkdir ${copydir}/srcdest
-#	mount -o bind ${SRCDEST} ${copydir}/srcdest
-#fi
-if [ ! -z "${SRCDEST}" ]; then
-	if ! grep 'SRCDEST="/srcdest"' "$copydir/etc/makepkg.conf" >/dev/null 2>&1; then
+if [[ ! -z "${SRCDEST}" ]]; then
+	[[ ! -d "$copydir/srcdest" ]] && mkdir -p "$copydir/srcdest"
+	if ! grep -q 'SRCDEST="/srcdest"' "$copydir/etc/makepkg.conf"; then
 		echo 'SRCDEST="/srcdest"' >> "$copydir/etc/makepkg.conf"
 	fi
-	[ ! -d ${copydir}/srcdest ] && mkdir ${copydir}/srcdest
+
 	mount -o bind ${SRCDEST} ${copydir}/srcdest
 fi
 
-[ -z "${MAKEFLAGS}" ] && eval $(grep '^MAKEFLAGS=' /etc/makepkg.conf)
-if [ -n "${MAKEFLAGS}" ]; then 
-  sed -i '/^MAKEFLAGS=/d' "$copydir/etc/makepkg.conf"
-  echo "MAKEFLAGS='${MAKEFLAGS}'" >> "$copydir/etc/makepkg.conf"
+if [[ -n $MAKEFLAGS ]]; then 
+	sed -i '/^MAKEFLAGS=/d' "$copydir/etc/makepkg.conf"
+	echo "MAKEFLAGS='${MAKEFLAGS}'" >> "$copydir/etc/makepkg.conf"
 fi
 
-[ -z "${PACKAGER}" ] && eval $(grep '^PACKAGER=' /etc/makepkg.conf)
-if [ -n "${PACKAGER}" ]; then 
-  sed -i '/^PACKAGER=/d' "$copydir/etc/makepkg.conf"
-  echo "PACKAGER='${PACKAGER}'" >> "$copydir/etc/makepkg.conf"
+if [[ -n $PACKAGER ]]; then 
+	sed -i '/^PACKAGER=/d' "$copydir/etc/makepkg.conf"
+	echo "PACKAGER='${PACKAGER}'" >> "$copydir/etc/makepkg.conf"
 fi
 
 if [ -n "${SUDO_USER}" ]; then
@@ -242,50 +363,62 @@ else
 	builduser=nobody
 fi
 
-[ -d ${copydir}/build ] && chown -R ${builduser} ${copydir}/build
-[ -d ${copydir}/srcdest ] && chown -R ${builduser} ${copydir}/srcdest
-[ -d ${copydir}/pkgdest ] && chown -R ${builduser} ${copydir}/pkgdest
+# Set target CARCH as it might be used within the PKGBUILD to select correct sources
+eval $(grep '^CARCH=' "$copydir/etc/makepkg.conf")
+export CARCH
 
-echo "${builduser} ALL = NOPASSWD: /usr/bin/pacman" > "$copydir/etc/sudoers.d/${builduser}-pacman"
-chmod 440 "$copydir/etc/sudoers.d/${builduser}-pacman"
+chown -R $builduser "$copydir"/{build,pkgdest,srcdest}
 
-#This is a little gross, but this way the script is recreated every time in the
-#working copy
-(cat <<EOF
+cat > "$copydir/etc/sudoers.d/nobody-pacman" <<EOF
+Defaults env_keep += "HOME"
+$builduser ALL = NOPASSWD: /usr/bin/pacman
+EOF
+chmod 440 "$copydir/etc/sudoers.d/nobody-pacman"
+
+# Set this system wide as makepkg will source /etc/profile before calling build()
+echo 'LANG=C' > "$copydir/etc/locale.conf"
+
+# This is a little gross, but this way the script is recreated every time in the
+# working copy
+cat >"$copydir/chrootbuild" <<EOF
 #!/bin/bash
+. /etc/profile
 export LANG=C
-cd /build
 export HOME=/build
-sudo -u ${builduser} makepkg $MAKEPKG_ARGS || touch BUILD_FAILED
-[ -f BUILD_FAILED ] && exit 1
-which namcap &>/dev/null && namcap /build/PKGBUILD /pkgdest/*.pkg.tar.* > /build/namcap.log
+
+cd /build
+sudo -u $builduser makepkg $makepkg_args || touch BUILD_FAILED
+
+[[ -f BUILD_FAILED ]] && exit 1
+
+if $run_namcap; then
+	pacman -S --needed --noconfirm namcap
+	for pkgfile in /build/PKGBUILD /pkgdest/*.pkg.tar.?z; do
+		echo "Checking \${pkgfile##*/}"
+		namcap "\$pkgfile" 2>&1 | tee "/build/\${pkgfile##*/}-namcap.log"
+	done
+fi
+
 exit 0
 EOF
-) > "$copydir/chrootbuild"
 chmod +x "$copydir/chrootbuild"
 
 if mkarchroot -r "/chrootbuild" "$copydir"; then
-	for pkgfile in "${copydir}"/pkgdest/*.pkg.tar.*; do
-		[ -e "$pkgfile" ] || continue
-		if [ "$add_to_db" -eq "1" ]; then
-			mkdir -p "${copydir}/repo"
-			pushd "${copydir}/repo" >/dev/null
+	for pkgfile in "$copydir"/pkgdest/*.pkg.tar.?z; do
+		if $add_to_db; then
+			mkdir -p "$copydir/repo"
+			pushd "$copydir/repo" >/dev/null
 			cp "$pkgfile" .
-			repo-add repo.db.tar.gz "$(basename "$pkgfile")"
+			repo-add repo.db.tar.gz "${pkgfile##*/}"
 			popd >/dev/null
 		fi
 	done
 else
-	#just in case. We returned 1, make sure we fail
-	touch "${copydir}/build/BUILD_FAILED"
+	# Just in case. We returned 1, make sure we fail
+	touch "$copydir/build/BUILD_FAILED"
 fi
 
-if [ -e "${copydir}/build/BUILD_FAILED" ]; then
-	echo "Build failed, check $copydir/build"
-	rm "${copydir}/build/BUILD_FAILED"
-	unbind
-	exit 1
+if [[ -e $copydir/build/BUILD_FAILED ]]; then
+	rm "$copydir/build/BUILD_FAILED"
+	die "Build failed, check $copydir/build"
 fi
-
-unbind
-
